create table easywork_contractor.contractor
(id bigint not null,
  create_date timestamp default current_timestamp comment '创建时间',
  creator varchar(50) default "" comment '创建者',
  effect_version varchar(50) default "0" comment '版本编号',
  is_del tinyint default 0 comment '是否删除',
  is_effect tinyint default 1 comment '是否生效',
  modifier varchar(50) default "" comment '修改者',
  modify_date timestamp default current_timestamp on update current_timestamp comment '更新时间',
  bank_account_no varchar(50) default null comment '开户行账号',
  bank_deposit varchar(50) default null comment '开户行',
  certification_category varchar(20) default null comment '认证类别',
  contact_man varchar(20) default null comment '联系人',
  contact_tel varchar(50) default null comment '联系电话',
  contractor_name varchar(50) not null comment '外包商名称',
  contractor_status varchar(20) default null comment '工程商状态',
  contractor_type varchar(20) default null comment '工程商类别',
  filing_date timestamp not null comment '纳入日期',
  project_area varchar(50) default null comment '可承接项目区域',
  project_type varchar(20) default null comment '可承接项目类型',
  referrer varchar(20) default null comment '推荐人',
  registered_fund decimal(11,2) default null comment '注册资金',
  serial_no varchar(50) not null comment '编号',
  primary key (id))
  engine=innodb