#spring:
#  datasource:
#    url: jdbc:mysql://10.1.248.147:3306/easywork_contractor?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#    username: easywork_platform
#    password: platform@1234
#  jpa:
#    properties:
#      hibernate:
#        default_catalog: easywork_console


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 15 #服务刷新时间配置，每隔这个时间会主动心跳一次 #默认30s
    lease-renewal-interval-in-seconds: 5 #eureka client刷新本地缓存时间 #默认30s
    prefer-ip-address: true #关闭自我保护
  client:
    serviceUrl:
      defaultZone: http://isdp:isdp_1234@10.1.248.147:8764/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true


easywork:
  security:
    jwt:
      secret: otherpeopledontknowit
      expiration: 3600
      prefix: Bearer
      header: Authorization
      url: /easywork/api/auth/login

server:
  port: 8091


logging:
  path: e:/
  file: e:/gateway.log