spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  messages:
    basename: BindingErrorMessages


zuul:
  prefix: /easywork/api/
  routes:
    platform:
      path: /platform/**
      serviceId: platform-server
    project:
      path: /project/**
      serviceId: project-server
    contractor:
      path: /contractor/**
      url: contractor-server
    gateway:
      path: /auth/**
      url: gateway-server

application:
  perPageLimit: 10

logging:
  path: e:/
  file: e:/gateway.log