spring:
  application:
    name: platform-server
  profiles:
    active: dev
  messages:
    basename: BindingErrorMessages

  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    driverClassName: org.mariadb.jdbc.Driver
    max-active: 20
    max-idle: 10
    min-idle: 1
    initial-size: 10
    tomcat:
      max-wait: 50000
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        hbm2ddl:
          auto: update
         # auto: create
    database-platform: com.dahua.tech.easywork.core.common.MySQL5DialectUTF8



application:
  perPageLimit: 10


logging:
  pattern:
    console: "%d - %msg%n"
  path: e:/
  file: e:/platform.log

fdfs:
  web-server-url: http://10.1.248.135:80/
  tracker-list: 10.1.248.135:22122
  thumb-image:
    width: 150
    height: 150
  pool:
    max-total: 200
  connect-timeout: 6000
  so-timeout: 3500

